nelmio_api_doc:
    documentation:
        info:
            title: Symfony API
            description: Demo Symfony API
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1(?!/doc) # Accepts routes under /api except /api/doc
